// Lista de frases — fácil de actualizar o ampliar
const frases = [
     "Ama cada detalle de tu vida; entrégate con amor; en todo hay un secreto de mayor intensidad de felicidad. Todo irá bien, confía y ama.",
    "Es cambiar preocupación por confianza. Ánimo, siempre viviendo la paz del Señor.",
    "La alegría siempre la da Dios.",
    "Que todo sirva para intensificar el amor recibido de Dios.",
    "La eficacia de todo se encuentra en el amor.",
    "En tu vida, dale tiempo al silenciamiento; es tu encuentro con lo importante.",
    "Solo se vive la sabiduría si la recibes de Dios.",
    "Llenarte de vida es llenarte de los dones de Dios. El camino se hace ligero.",
    "Si te entregas a la voluntad de Dios, abres las puertas a la paz.",
    "Pon el gozo de la paz que recibes de Dios en todos tus afanes.",
    "Toda fuerza viene del Señor; a Él nuestra mirada.",
    "Nuestra tarea, nuestra misión, nuestra sabiduría: ser testimonio de los deseos de Dios en toda tu realidad.",
    "Mira siempre esa luz especial que nunca se apaga.",
    "Caminar siempre en la acogida es contemplar el milagro de la transformación de toda nuestra vida.",
    "Si tu vida es un don, siempre tendrás alegre el corazón.",
    "Deja que el Señor dirija tu vida; siempre darás la melodía más hermosa.",
    "Haz de tu vida una actitud de escucha.",
    "Ama con gratuidad y siempre descubrirás al que sufre.",
    "Lo grande es llevar las cargas de nuestra vida desde la suavidad.",
    "La paciencia es tal si se reviste de amor.",
    "Todo se oscurece si bebemos de la fuente que se agota.",
    "Siempre con Dios, en el descanso del alma.",
    "Nuestra debilidad es el campo de Dios.",
    "No lo olvides, todo debe intensificar nuestra comunión con Dios y los hermanos.",
    "La presencia de Dios nos reviste de serenidad y ligereza.",
    "Que de tu corazón siempre salga la palabra gracias.",
    "La primera impresión suele ser un engaño. El corazón contemplativo descubre lo importante.",
    "La humildad hace brillar nuestra vida con todas las virtudes.",
    "Lo importante es tener claridad en el interior.",
    "Con Dios, aprendemos a mirar con bondad y amor.",
    "Tu Maestro, el Señor. Siempre se encuentra el camino.",
    "Experimenta la visión nueva que Dios, cada día, te regala.",
    "El triunfo en todos los frentes es privilegio del amor.",
    "Si tienes un corazón confiado, tus fuerzas son infinitas.",
    "Todo, en el fondo y en la forma, nos invita al amor.",
    "Que toda tu vida rezume esperanza.",
    "El vigor y la fuerza son fruto de la mirada de Dios.",
    "El verdadero descanso es privilegio del corazón que escucha los secretos de Dios.",
    "Las sorpresas de Dios son consecuencia de su escucha.",
    "La claridad y la facilidad son regalos del Señor.",
    "La fuente de la sanación se encuentra en el diálogo con el Señor.",
    "En la entrega sin reservas aparece la paz.",
    "Ama lo que te sucede; Dios, ahí, te acompaña y te habla.",
    "Lo que da sentido a todo es la presencia del amor.",
    "El Señor, en el domingo, siempre te habla sobre lo que te conviene.",
    "Dios, con su presencia, nos regala su paciencia.",
    "Dios es imprevisible hasta con el regalo de la paz.",
    "Todo es oportunidad de intensificar la escucha.",
    "En todo momento y en toda circunstancia, los hermanos en primer plano.",
    "Las maravillas las hace Dios en quien en Él confía.",
    "Sé peregrino de amor; todo brilla y madura si, con amor, dejas que pase.",
    "Deja que el fuego del amor de Dios penetre en tu corazón.",
    "Ten siempre una mirada de bondad y de amor; es lo único que vale.",
    "Que tu vida sea reflejo del silencio sonoro de Dios.",
    "Amor y silencio son la comunión perfecta.",
    "Lo sabio y útil es sentirse amado por Dios.",
    "A lo poquito que nosotros le damos, Dios responde con su generosidad sin medida.",
    "Atento a la escucha de Dios; su voz se mezcla en todo lo que te acontece.",
    "Siempre se dice lo oportuno si se dice desde la paz.",
    "Que toda tu vida respire el ambiente de Dios.",
    "Tu vida se enriquece si hace felices a los demás.",
    "Dios ama nuestra sencillez y pobreza.",
    "La plegaria es la fuente que nunca se agota.",
    "Solo el encuentro con Dios y con los hermanos da plenitud a nuestra vida.",
    "Si nuestra respuesta es de amor, siempre acertaremos.",
    "Salir de nosotros mismos es privilegio del amor.",
    "Todo en tu vida muestra un nuevo camino de amor.",
    "La oscuridad es fruto de la mediocridad. La luz aparece en la entrega.",
    "Dios habla contigo.",
    "Dios habla contigo si eres fiel en las cosas pequeñas.",
    "Dios te mira con bondad; ese es tu camino.",
    "La fuerza y la vida están en la paz que recibes de Dios. Supera todas tus dificultades.",
    "Tu paz sea el reflejo de la voluntad de Dios.",
    "No son opiniones; nuestra vida es fe y abandono en quien es respuesta a todos nuestros deseos.",
    "Nunca hay soledad para quien en Dios confía.",
    "Si ponemos delante el nosotros, siempre hay acogida.",
    "La paz es alejarse de tantos ídolos.",
    "La alegría está y radica en la esperanza.",
    "Guarda la calma y la paz en toda situación; ese es el camino.",
    "Dios es felicidad y claridad si a Él te abandonas.",
    "Solo el amor transforma el sufrimiento.",
    "La escuela del amor reside en el sufrimiento.",
    "Descubre quién contempla.",
    "La claridad del camino la da la escucha.",
    "La fuerza más grande que siempre te acompaña es la fraternidad.",
    "Tu vida es siempre novedad creadora con Dios y con los hermanos.",
    "Con Dios, solo existe descanso en el alma.",
    "Tu amistad con Dios, fuente de todos los gozos.",
    "El gozo de servir es la liberación de la mente.",
    "Todo fracaso queda sanado si nos acompaña la confianza del Señor.",
    "Nada resiste a la fuerza de la oración.",
    "Es el camino que se nos muestra: Dios y los hermanos. No existe la soledad.",
    "Todos los conflictos se minimizan ante la vivencia de la fraternidad.",
    "La presencia de Dios solo es y siempre amorosa.",
    "Desde la pequeñez todo es claridad.",
    "El amor y el corazón libre caminan juntos.",
    "Si en todo pones la paz del Señor, tu fuerza y victoria están garantizadas.",
    "Toda claridad fluye de la oración.",
    "Si en tus dificultades llenas de paz a los demás, es la prueba evidente de que Dios está contigo.",
    "El Señor es tu paz.",
    "El Señor es la paz que nunca falla.",
    "Que Dios te acompañe con su luz y su paz en estos momentos.",
    "Lo importante es tener el espíritu siempre dispuesto a recibir los dones de Dios. Adelante.",
    "Sé paciente; la paciencia es la gran virtud que permite escuchar los pasos de Dios.",
    "Todo, con la fe, se convierte en un gran encuentro de amor.",
    "Tu vida es de alegría si en todo alabas al Señor.",
    "En todo momento, gracias a Dios.",
    "La respuesta válida la da Dios con la plegaria; Dios es fiel.",
    "La felicidad está en todo lo que tienes al alcance de la mano.",
    "La bienaventuranza es caminar con Dios.",
    "Tu realidad es sentirte, con el Señor, bienaventurado.",
    "Es muy sencillo; en la plegaria Dios siempre te da más.",
    "Solo Dios es dador de aquello que nos sobrepasa; solo Él quiere ser el protagonista.",
    "Dios llena a quien se entrega; ese es el camino de la paz.",
    "Para Dios, no existen las cargas; Él es bondad y delicadeza.",
    "Si los demás son los protagonistas, ese día lo has aprovechado.",
    "No lo olvides, la paz y el amor no los conseguimos nosotros; son regalo del Señor.",
    "En la constancia se realiza el milagro de nuestra madurez y paz.",
    "El cansancio no tiene ninguna fuerza si te acompaña la plegaria.",
    "La plegaria te hace escuchar el murmullo de amor de Dios.",
    "No te alejes del Espíritu; encontrarás el camino que te conviene.",
    "Todo egoísmo o interés personal se diluye ante la fuerza del Espíritu.",
    "Nuestro castillo interior es inexpugnable si experimentamos la fuerza de ser familia divina.",
    "La validez y eficacia de tu vida te las marca el amor con que vives todo cuanto te acontece.",
    "Una gran fiesta de Todos los Santos; es nuestro camino y nuestra paz.",
    "Tu vida siempre brillará si le acompaña la esperanza.",
    "Vivir la paz es llenarse de agradecimiento y confianza.",
    "Ser fieles al Señor nos abre las puertas de la claridad. El secreto de la sabiduría, Dios lo coloca en tu confianza en Él.",
    "Siempre optar por el bien; Dios te acompañará con su gozo y satisfacción.",
    "Lo que quita todos los miedos es la confianza en el Señor.",
    "Que tu plegaria sea siempre por los demás; esa es la fuente de la eficacia de tu vida.",
    "La felicidad es tu abandono en Dios.",
    "El amor de Dios es la fuerza que todo lo convierte en luz.",
    "Sé constante y paciente; ahí, siempre aparece la paz.",
    "Es muy sencillo; Dios lo hace así, al alcance del corazón. Siembra del amor de Dios toda tu vida y te acompañará el gozo.",
    "Lo que de verdad eres es lo que te da la paz.",
    "Experimenta el gozo de dejar en manos de Dios todo lo que no podemos controlar. Es el descanso del alma.",
    "Lo que da alas al corazón es la esperanza.",
    "Dar a los demás lo oportuno es consecuencia de nuestro contacto con Dios.",
    "Siempre escucha; Dios es la voz más clara y más poderosa.",
    "A quien hay que escuchar es a Dios y empieza por renunciar a uno mismo.",
    "Un corazón libre siempre discierne las necesidades de los demás.",
    "No lo olvides, tu seguridad y tu paz son la misericordia del Señor.",
    "Mira el árbol de la cruz; todo en Él se suaviza.",
    "El Cristo Rey pone su trono en nuestro corazón; esa es nuestra seguridad y fuerza.",
    "Nuestra vida debe ser un constante e infinito amor a los demás; así nos ama el Señor a nosotros.",
    "Goza, disfruta de tener un corazón lleno de bondad. Todo será bueno.",
    "En tu vida, siempre presentes: Dios y los hermanos.",
    "Vive con intensidad cada momento de tu vida; contiene todo lo que necesitas para ser amado y para amar.",
    "Me alegro; una gran bendición de paz y bien.",
    "Es tu capacidad de escucha tu verdadera riqueza.",
    "Tu vida será claridad si es el Señor quien la ilumina.",
    "Es muy importante: no seamos maestros de nosotros mismos; si somos discípulos, sabremos leer siempre los mensajes de cuanto nos acontece.",
    "Es la intensidad de tu interior quien aligera el camino exterior.",
    "Lo que da brillo a nuestros ojos es la virtud de la esperanza.",
    "Muy importante: siempre Dios, el protagonista; todo vuelve a su orden.",
    "De todo es el Señor quien inspira cada pensamiento.",
    "Atiende a este signo de la fe; si nuestro conflicto es intenso, es que estamos en soledad; Dios es siempre compañía y nos regala su suavidad.",
    "El camino de la alegría y la paz lo va marcando nuestra entrega generosa a la voluntad de Dios.",
    "A escuchar lo que conviene nos lo muestra la intensidad de nuestra plegaria.",
    "Nunca decaigas; tu desierto es el trono en el que Dios realiza el milagro de tu transformación.",
    "Nuestro camino es la pequeñez, la humildad; Dios ya hará sus maravillas.",
    "Nuestra vida es un continuo reto a superar; siempre aparece la luz si hay paciencia y confianza.",
    "Experimentar la paz del Señor es experiencia del suave caminar.",
    "Solo la paz te da la verdadera lectura de tu vida.",
    "Haz la prueba; deja que la mirada misericordiosa repose en tu vida y la paz brillará en tu corazón.",
    "Ese fuego interior que todo lo sana es la alegría que te regala el Señor.",
    "Dios es tu intimidad; es ahí donde está tu verdadera compañía.",
    "La Navidad es el libro abierto que hemos de aprender a leer; contiene todos los secretos reales de nuestra felicidad.",
    "Lo que recibimos del Señor es la fuerza que nos hace atravesar todas nuestras dificultades.",
    "Todo se lee correctamente si es Dios quien preside nuestra vida.",
    "Sé generoso en la entrega, sin reservas; es la garantía de que nunca te faltará luz en tu camino.",
    "Siempre nuestra vida llega a su plenitud con los hermanos. Son la presencia viva de un Dios que, con ellos, nos acompaña.",
    "La fraternidad convierte los conflictos en motivo de crecimiento.",
    "Todo se vive y se saborea en el interior.",
    "En la Navidad se refleja, con claridad, la verdad de tu vida. Contempla siempre la Navidad.",
    "Es Dios quien te ha escogido con su ternura; eso lo llevas en tu corazón; derrámala sobre los demás.",
    "Tu acompañante, el que es eficaz, es el ESPÍRITU de la Navidad. Ahí está toda la novedad.",
    "Con la Navidad se descubre el gozo que nunca se acaba.",
    "Todo lo que Dios deposita en tu corazón llega a su plenitud cuando ves que brilla en los demás.",
    "Distinguimos la luz del Señor porque es comunión con los hermanos.",
    "Mira con amor tu familia; es la cuna del amor de Dios; vuestro amor es la aportación más hermosa que podéis hacer a la Iglesia y al mundo. Felicidades.",
    "La claridad nace en la escucha a Dios y a los demás.",
    "El gozo hace su morada en ti si das a los demás lo mejor de ti mismo.",
    "Ábrete al nuevo regalo que el Señor te ofrece con este nuevo año. Sin miedo, entra, con amor, a todo lo que el Señor te ofrece y te ofrecerá.",
    "Dios confía en ti; y lo que Dios quiere es convertir toda tu vida en bendición constante y amor sin reservas.",
    "Lo que manifiesta un corazón pacificado es un GRACIAS sin reservas.",
    "Con Dios, la vida es suave y ligera; Él siempre es liberación. Si, en cambio, duele, hay que cambiar de dirección.",
    "La alegría se intensifica cuando te sumerges en la luz del Señor.",
    "La humildad de tu corazón te abre a la infinitud del don de la paz del Señor.",
    "Que tu vida esté llena de la gran revelación de la Epifanía.",
    "Los actos, en sí mismos, son fríos; el corazón es el que los llena de vida.",
    "Acoge lo sencillo de cada día; contiene toda tu felicidad.",
    "Lo que constituye el verdadero gozo del corazón es dar sin reservas y gratuitamente.",
    "Solo hay que estar atento al Espíritu; Él nos muestra el camino de la paz.",
    "Toda la fuerza del Espíritu mora en nuestro corazón. Por eso somos familia de Dios, comunión y escucha.",
    "La paz real, la que Dios te ofrece, la has de ver reflejada en los demás. Ese es su destino.",
    "Todo lo que ames y a quien ames, todo se convierte en felicidad.",
    "Recuerda siempre tener una plegaria de agradecimiento por nuestros sacerdotes.",
    "Ama lo que es tu historia; siempre contiene el gozo de un nuevo amanecer.",
    "Que tengas siempre esos momentos de silencio sonoro; son los que te enseñan el camino de la palabra eficaz.",
    "Eres profeta del Señor si reflejas en tu vida lo mucho que de Él recibes.",
    "El sagrario de nuestra felicidad y paz se encuentra en nuestro interior; pues bien, eso que vivimos en nuestro interior es lo que debemos dar a los demás.",
    "Los límites los ponemos en nosotros; con Dios, todo es infinitud al alcance de la mano.",
    "Alimenta siempre tu confianza en el Señor. Es la que abre los nuevos caminos.",
    "El camino de tu paz siempre empieza en tu interior.",
    "Los frutos aparecen en la entrega generosa.",
    "Si te acompaña siempre y en todo una alabanza al Señor, te dirige la paz.",
    "Deja que entre la sabiduría de Dios en tu parcela profundamente humana.",
    "Confía; tu respuesta, la que te conviene, es fruto de tu diálogo con el Señor.",
    "Todo lo recibes de Dios; todo lo saborearás si se lo ofreces a Él.",
    "Dios se hace visible y claro en nuestro amor a los hermanos.",
    "De Dios y de los hermanos es de quienes recibimos la fuerza que nos conviene en nuestro caminar. Con ellos, no hay cansancio.",
    "La fuerza en tu vida es la compañía fiel del Señor.",
    "La escucha de Dios es el camino más eficaz para enriquecernos con los hermanos.",
    "La dificultad nunca tiene la última palabra; escucha a Dios que todo lo transforma en agradecimiento.",
    "Que el Espíritu de Jesús sea tu norte, guía y maestro; la felicidad siempre estará llamando a tu corazón.",
    "En Dios, todo se magnifica; ya ves, tu pequeñez, tu insignificancia, tu anonimato, Dios lo convierte en luz de las naciones.",
    "Las sombras son nuestro trabajo mal enfocado; con el Señor, todo es claridad.",
    "Tu fortaleza es Dios; ten siempre claro esto; todo participa de esta hermosa cualidad.",
    "Es el yo el creador de dudas, tropiezos y nubarrones.",
    "Que siempre nuestro sufrimiento esté con el Señor; nos convertimos en corredentores.",
    "Solo hay una luz que de verdad brilla: es la del corazón. Esa es la tuya.",
    "Tu entrega generosa marcará la intensidad de tu felicidad. Dios nos muestra ese camino.",
    "Toda tu vida debe estar poseída por la paz del Señor que se te regala.",
    "Caminar por la senda justa es privilegio de nuestra vida mirada a Dios con intensidad; y todo es suavidad y ternura.",
    "Experimenta que Dios se enternece ante tu confianza y amor.",
    "Es el tiempo que siempre nos regala paz; es el tiempo que dedicamos a la intimidad con el Señor.",
    "El camino está muy claro; Dios lo marca en las necesidades de los demás.",
    "Atento a quién abres la puerta de tu interior; solo lo que te hace bien tiene derecho de entrada.",
    "Dios nos muestra dónde se encuentra su presencia; amarlo a Él es amar a los hermanos en donde se encuentra presente.",
    "Es cuestión de mirada; mira a Dios y es infinito lo que recibes.",
    "Dios sabe lo que es lo que nos conviene; por eso, se manifiesta en una vida sencilla.",
    "La Cuaresma es esa puerta abierta a los dones de Dios que son los que has de ofrecer a los demás.",
    "Huye de las apariencias; son las que crean la oscuridad del corazón.",
    "Nunca renunciemos a ser felices; es Dios quien nos ha puesto esta opción.",
    "Que nada pese en tu vida; es Dios quien libera y lo empequeñece todo.",
    "La mayor claridad a tu corazón es privilegio de la voz de Dios que resuena en la Cuaresma y hace brillar todo lo que nos conviene.",
    "El dar sabiduría a los demás es consecuencia de una vida vivida en plenitud.",
    "Si entras en el silencio, el camino es siempre el correcto y oportuno.",
    "Es en tu disponibilidad y vacío que se muestra la verdad de Dios.",
    "La alegría nace y se desarrolla en la entrega generosa.",
    "Lo grandioso es que tu vida sea reflejo de la voz del Señor que resuena en tu corazón.",
    "Vive esa experiencia de ausencia de miedo y de toda adversidad... Esa es la presencia de Dios.",
    "La perla preciosa es la fraternidad; a través de ella llegan las sorpresas de Dios.",
    "Lo que pesa en la vida es que el amor de Dios no dirija nuestra vida.",
    "Nada puede sustituir al Dios que armoniza nuestra vida.",
    "Es la gran experiencia: lo poco, Dios lo convierte en infinitud.",
    "Es la tuya, tu historia; esa es la que contiene tu paz y felicidad.",
    "Nuestra misión es escuchar; ahí está lo que nos conviene.",
    "Dios quiere depositar todos sus dones en tu corazón. Él sacia todos los anhelos.",
    "Lo propio de Dios es darte; esa es su alegría.",
    "Tu vida sencilla es la que hace que Dios sea claridad.",
    "El secreto es la constancia; si a ella identificas la confianza, la fidelidad del Señor se hace viva y real.",
    "Dios es el que, de verdad, nos muestra siempre el camino del gozo.",
    "Huye de todo aquello que produce ruido en el corazón.",
    "El camino del gozo y de la paz lo muestra tu acogida y comprensión.",
    "Ábrete a la mirada del corazón; es la que penetra todos los secretos de Dios.",
    "Nada de miedos; Dios ha triunfado; esta victoria se ha de hacer presente en tu vida.",
    "Cuida siempre tu mente; siempre limpia y en paz; todos tus actos serán claridad.",
    "Es Dios quien te marca su ritmo, el que conduce a tu felicidad.",
    "Dios quiere que todo llegue a su plenitud por el camino de la ternura.",
    "Tu vida siempre mirando a la felicidad de los demás.",
    "Las sombras nos llegan cuando olvidamos la fuente; y la fuente es el amor de Dios encarnado en nuestro corazón.",
    "La victoria es del Señor; y estar con Él es entrar en la victoria de la resurrección y de la vida.",
    "Es el Señor quien nos hace perder el miedo al sufrimiento; Él nos acompaña y lo transforma.",
    "El camino es entregarte al amor y dejar que se apodere de ti; todo se restaura.",
    "El Señor nos enseña a discernir aquello que debemos escuchar.",
    "Es claro y real; de Dios te viene la paz; de nosotros nos viene el cansancio.",
    "No te escuches solo a ti mismo; ahí no se encuentra la respuesta que te conviene.",
    "Que nunca la oscuridad del momento oscurezca la claridad de tu entrega. Lo experimentarás en el resultado.",
    "No creas en lo que piensas o en lo que deseas; lo que todo lo aclara es la intensidad del amor que mora en tu corazón.",
    "Que tu vida sea CONTEMPLAR; Dios está haciendo de la pequeñez de tu vida una realidad divina, y de cada uno de tus actos, una plenitud verdaderamente humana.",
    "Sé siempre fiel al Señor; cada día, cada momento; escucharás la voz que te conviene.",
    "El arma que nos hace mirar con esperanza toda nuestra vida es el amor. Esa es nuestra gran aventura y reto.",
    "Toda tu vida con el Señor es una celebración de amor.",
    "Dios brilla en nuestra vida cuando su amor transforma nuestro sufrimiento en gozo.",
    "Con el silencio, aparece Dios con su claridad.",
    "No lo olvides, irás seguro con la fuerza del Cristo resucitado.",
    "No es un recuerdo la Pascua; si esta te acompaña, es tu vida la que se convierte en una constante Pascua.",
    "Vive la Pascua; no solo unos días; toda nuestra vida debe ser y manifestar la alegría de la Pascua.",
    "El camino del Señor siempre es el más claro y sencillo; descubierto, el Señor nos dice nuestro nombre y nos transforma.",
    "Y es que Jesús nos lo ha mostrado con toda claridad; todas las luces de la felicidad están encendidas si el amor de Dios mora en nuestro corazón.",
    "No desvíes tu mirada; céntrala en tu camino; Dios lo ha detallado para tu felicidad.",
    "Este es el camino: da paz generosamente y, a raudales, Dios te regalará la suya.",
    "Deja que Dios presida tu vida y aparece la fiesta.",
    "El Cristo resucitado nos da una alegría que nunca conoce el ocaso; siempre mora en nosotros.",
    "El mimo de la mente y el cuidado del corazón es privilegio de Dios.",
    "Que en tus silencios tengas una plegaria especial por los sacerdotes.",
    "Esto no hay que olvidarlo; la eficacia a todos los niveles nace en tu intimidad con el Señor.",
    "La mirada del corazón es la que transforma el Señor; con ella siempre se encuentra el camino del dar, regalar y ofrecer.",
    "Dios te pide que salgas de ti mismo; sus sorpresas aparecen en este camino.",
    "Esta es la novedad de tu vida: que, en ella, siempre dirija el amor y la resurrección.",
    "Dios siempre nos llena de lo que nos conviene si nuestro corazón está abierto a Él.",
    "Cada momento es el oportuno, el importante; es el espacio en el que se debe intensificar el amor que recibes de Dios.",
    "No te distraigas; a todo y en todas circunstancias, la respuesta que te conviene viene del Señor.",
    "Quien da vida solo es el Señor; esta es la claridad.",
    "A veces nos cuesta aprender lo que, de verdad, necesitamos. Es muy sencillo: Jesús, la fuente; solo Él; nuestro yo, ver cómo se diluye en sus manos.",
    "Siempre a la escucha de la voz del buen Pastor. Otras voces no interesan.",
    "El Señor, para que no haya confusión, nos llama con nuestro nombre. Cuando eso lo oímos, ya nunca se nos olvida la voz del Señor.",
    "Tu firmeza radica única y exclusivamente en tu corazón bien alimentado.",
    "Dos realidades se identifican: abandonarnos en el Señor y experimentar cómo, de esta manera, Él realiza en nosotros lo que nos es imposible.",
    "Más allá de nuestras apariencias, se encuentra el Señor.",
    "En la vida de fe, todo es confianza; confía y el Señor te regala el camino que te conviene.",
    "Que tu acompañante sea siempre tu silencio interior.",
    "Es signo de sabiduría especial; distingue siempre esa luz que \"siempre\" ilumina tu vida.",
    "Que siempre y a pesar de todos los pesares, tu corazón rebose de agradecimiento.",
    "No es una cuestión mental; la verdad se vive con la identificación con el Señor.",
    "La verdad del Señor va por el camino de la humildad y servicio a los demás.",
    "La fuente que mana, corre y nunca se agota; esa es la que Dios nos muestra y proporciona.",
    "Huye de tus interpretaciones; escucha en tu interior; esa voz es clara y sorpresiva.",
    "Nuestra vida Dios la ha diseñado para que sea un mar, a veces embravecido; eso no importa, de amor y de paz.",
    "Siempre en manos de María y del Señor.",
    "La claridad, el perdón, la paz, todo confluye y se aglutina en nuestra vida cuando dirige el amor de Dios.",
    "Recuerda, Dios todo nos lo pone fácil y sencillo; lo que pasa de ahí es porque queremos controlar; y eso... no es nuestra tarea.",
    "La verdadera mirada te la da la fe; con ella, todo se aligera.",
    "Nuestro camino es claro; es aquel en el que caben todos los hermanos.",
    "El ver con claridad es eliminar nuestro yo, que es dificultad.",
    "El camino que todo lo ilumina es: amar; ahí se encuentra la eficacia.",
    "Todo nos lo ha merecido el Señor; nosotros somos su victoria ahora y en un futuro.",
    "A veces, no vivimos en nuestra propia casa. Atentos: en nuestra vida, nuestra propia casa es donde tenemos todas las experiencias agradables de nuestra vida. Esa casa la ha diseñado Dios para ti.",
    "Dios es el que hace que aceptemos y amemos; ese es el camino de la paz.",
    "De Dios siempre recibimos plenitud.",
    "La alegría que recibimos del Señor es infinitamente superior a todo lo que nos puede hacer decaer.",
    "Eres profeta del amor y paz del Señor.",
    "Tu verdadero ser te lo quiere recrear el Espíritu con sus enseñanzas y recuerdos.",
    "El camino está claro: el Espíritu en nuestro corazón nos envía y hace sencilla, fácil y eficaz toda nuestra vida.",
    "No hay noches con el Señor.",
    "Dar sin medida es el camino de nuestra vida, plenitud y madurez.",
    "Ese es el milagro; Dios te da su mirada y toda tu vida se convierte en luz que nunca se apaga.",
    "Con Dios presente, a TODOS convertimos en hermanos.",
    "Un corazón abierto y liberado; siempre te encontrarás, de frente y de bruces, con la alegría del Señor.",
    "No mires hacia otro lado; solo si todo lo haces por amor, tienes la respuesta feliz a todo lo que vives.",
    "La belleza de nuestra entrega aparece cuando todo lo acompañamos con el amor.",
    "Todo es gozo y paz con el amor de Dios y la libertad.",
    "El camino es claro; deja las apariencias y brilla la paz.",
    "Un momento presente, en manos de Dios, es la plenitud de la paz. Y eso... es eterno.",
    "La cuna y el jardín de la alegría es: la sencillez y la entrega.",
    "Nosotros caminamos en el amor; vivimos sumergidos en el amor; esto es posible porque nos alimentamos con el Pan de Vida.",
    "Deja que Dios sea el Maestro; siempre es descanso en el corazón.",
    "La verdadera fuente del corazón es la Eucaristía. Sabe identificar PLENITUD Y PEQUEÑEZ.",
    "Es tan grande lo que Dios nos pide que solo con su alegría podemos llevarlo a cabo. Abiertos a la alegría de Dios.",
    "El equilibrio perfecto y claro es este: amor a Dios y a los hermanos.",
    "Todo tiene un camino concreto y equilibrado; recibes de Dios, lo ofreces a los demás y vuelve a Dios. Esa es la paz.",
    "Solo ese detalle; si dejamos lo que, inútilmente, nos domina, aparece la belleza y armonía de lo que Dios hace en nosotros.",
    "No eches a perder el momento presente de amor por un futuro del que no tienes garantía.",
    "Camina en el amor y experimentarás el gran milagro: todo lo más insignificante de tu vida será sabiduría y gozo.",
    "Dios te elige para que seas portador de sanación en las heridas de los demás.",
    "Esta es la eficacia: toda tu vida ha de ser un ambiente de paz y de alegría.",
    "No hay confusión; la relación con Dios es la claridad del corazón.",
    "Escuchar a Dios con claridad es adentrarse en el camino de la paz.",
    "Lo que produce sequedad en el corazón es: vivir de apariencias.",
    "Tu vida es plena y siempre lo será si, a todo y en toda circunstancia, das una respuesta de amor.",
    "Contempla, mira fijamente; tu seguridad es viva y real si eres consciente de la presencia de Dios que, en todo momento, te acompaña.",
    "Confiar en Dios es escuchar, en cada momento, aquello que te conviene.",
    "Escuchar aquello que nos conviene es un gran ejercicio de liberación personal.",
    "Una vida sencilla y humilde es la cuna de una escucha clara de aquello que te conviene. Esa es la luz que nunca se acaba.",
    "No hay resquicio de sombra; la fe es claridad y sabiduría en cada uno de tus pasos.",
    "Que sepas disminuir para que sea Él quien resucite siempre en tu vida.",
    "A veces nos olvidamos de lo esencial y sencillo; lo que nos hace caminar en paz es el alimento del corazón.",
    "Si tu mirada es de misericordia, todo lo llenarás de luz.",
    "No hay comparación posible entre lo que Dios nos regala y las pruebas que nos acontecen.",
    "Dios todo lo deposita en la familia; ahí, todos aprendemos a experimentar lo que nos conviene.",
    "En nuestra vida, el gracias debe superar a las exigencias.",
    "La victoria es del interior en calma. Ese es el camino.",
    "Dios y la humildad son el mismo camino. No admiten confusión.",
    "Lo que pesa nunca es de Dios; su camino es ligereza y suavidad.",
    "No hay muro que resista a la ternura que Dios quiere depositar en nuestro corazón.",
    "Una mirada sencilla lee todo con claridad.",
    "No olvides, siempre en Dios está nuestro verdadero descanso.",
    "Si todo está en su lugar, no hay cargas.",
    "A leer correctamente el amor se aprende con la humildad.",
    "Camina con Dios; nunca falta la luz y la respuesta que conviene.",
    "El secreto de todo gozo radica en el corazón evangélico.",
    "La alegría profunda se experimenta haciendo siempre el bien.",
    "En Dios no cabe otra cosa; quiere tu gozo y paz.",
    "En la tierra de tu corazón, Dios ha depositado toda la sabiduría de tu felicidad. Nuestra opción es: descubrirla.",
    "El amor destruye las apariencias; el amor es el camino del verdadero conocimiento.",
    "Cuando experimentas en tu corazón que todo lo recibimos de Dios, la paz inunda todo nuestro ser.",
    "Que tu raíz sea la plegaria; todo se ilumina.",
    "La mirada en la Virgen del Carmen es una invitación a desconfiar de nosotros mismos; Ella nos muestra el verdadero camino.",
    "No existe la soledad; Dios y los hermanos son nuestra plenitud.",
    "Con los ojos de la humildad, todos los panoramas vuelven a su verdadera realidad.",
    "Con Dios, la dificultad se hace fácil.",
    "De nuestro desierto Dios hace un jardín.",
    "Que todas nuestras dudas se serenen con el Señor.",
    "Si del camino no gozamos, no es del Señor.",
    "A la esperanza siempre debe acompañar la fuerza de la fe.",
    "Una gran noticia: ya podemos volver a casa.",
    "Todo resplandece cuando domina y dirige la fraternidad. Ya en casa, todo en perfectas condiciones.",
    "La felicidad es la consecuencia de llenarse de amor y perdón.",
    "Atento, presta atención; fíate del Señor; hoy, te regala este día para que te entregues a vivir sus dones.",
    "Todo son cargas cuando Dios se ausenta de nuestro horizonte.",
    "Quien vence en todos los frentes es un interior por Dios habitado.",
    "La luz de tu corazón se intensifica cuando la proyectas sobre las oscuridades de los demás.",
    "Llena tu corazón con tantos dones que Dios te regala. Sé consciente de ello.",
    "Quien llena de vida y esperanza segura y cierta es la presencia del Señor.",
    "Pon tu debilidad en la plegaria. Es tu fuerza y tu amor.",
    "Ten un corazón libre y pobre; siempre brillará el milagro del amor.",
    "Dios es nuestra serena y eficaz compañía.",
    "Sigue a Jesús, mira a Jesús; no cabe la tristeza, no cabe el desaliento. Contempla al Señor.",
    "Tu fuerza es que el amor de Dios siempre te acompañe.",
    "Ay, Señor, el Señor es nuestra fuerza y salud. Todo, gracias a Dios, que el Señor nos quiere en paz y con el gozo en el corazón.",
    "Todo se lee correctamente si descubrimos el mensaje de amor que nos transmite.",
    "Dios y los hermanos son nuestro sostén y fortaleza.",
    "Todo lo que damos a los demás es eficaz si antes lo hemos experimentado nosotros.",
    "No busques solo; aparecen multitud de cosas y caminos; tu conversación constante con el Señor te mostrará la verdad de lo que vives.",
    "Lo que da vida es que todos tus actos solo tengan motivación de amor.",
    "Lo que el Señor desea que le regales es: TU DEBILIDAD; es Él quien la transforma en fortaleza."
];