// Lista de frases — fácil de actualizar o ampliar
const frases = [
    "Ama cada detalle de tu vida; entrégate con amor; en todo hay un secreto de mayor intensidad de felicidad. Todo irá bien, confía y ama.",
    "Es cambiar preocupación por confianza. Ánimo, siempre viviendo la paz del Señor.",
    "La alegría siempre la da Dios.",
    "Que todo sirva para intensificar el amor recibido de Dios.",
    "La eficacia de todo se encuentra en el amor.",
    "En tu vida, dale tiempo al silenciamiento; es tu encuentro con lo importante.",
    "Solo se vive la sabiduría si la recibes de Dios.",
    "Llenarte de vida es llenarte de los dones de Dios. El camino se hace ligero.",
    "Si te entregas a la voluntad de Dios, abres las puertas a la paz.",
    "Pon el gozo de la paz que recibes de Dios en todos tus afanes.",
    "Toda fuerza viene del Señor; a Él nuestra mirada.",
    "Nuestra tarea, nuestra misión, nuestra sabiduría, ser testimonio de los deseos de Dios en toda tu realidad.",
    "Mira siempre esa luz especial que nunca se apaga.",
    "Caminar siempre en la acogida es contemplar el milagro de la transformación de toda nuestra vida.",
    "Si tu vida es un don, siempre tendrás alegre el corazón.",
    "Deja que el Señor dirija tu vida; siempre darás la melodía más hermosa.",
    "Haz de tu vida una actitud de ESCUCHA.",
    "Ama con gratuidad y siempre descubrirás al que sufre.",
    "Lo grande es llevar las cargas de nuestra vida desde la suavidad.",
    "La paciencia es tal si reviste de amor.",
    "Todo se oscurece si bebemos de la fuente que se agota.",
    "Siempre con Dios, en el descanso del alma.",
    "Nuestra debilidad es el campo de Dios.",
    "No lo olvides, todo debe intensificar nuestra comunión con Dios y los hermanos.",
    "La presencia de Dios nos reviste de serenidad y ligereza.",
    "Que de tu corazón siempre salga la palabra gracias.",
    "La primera impresión suele ser un engaño. El corazón contemplativo descubre lo importante.",
    "La humildad hace brillar nuestra vida con todas las virtudes.",
    "Lo importante es tener claridad en el interior.",
    "Con Dios, aprendemos a mirar con bondad y amor.",
    "Tu Maestro el Señor. Siempre se encuentra el camino.",
    "Experimenta la visión nueva que Dios, cada día, te regala.",
    "El triunfo en todos los frentes es privilegio del amor.",
    "Si tienes un corazón confiado, tus fuerzas son infinitas.",
    "Todo, en el fondo y en la forma, nos invita al amor.",
    "Que toda tu vida rezume esperanza.",
    "El vigor y la fuerza son fruto de la mirada de Dios.",
    "El verdadero descanso es privilegio del corazón que escucha los secretos de Dios.",
    "Las sorpresas de Dios son consecuencia de su escucha.",
    "La claridad y la facilidad son regalos del Señor.",
    "La fuente de la sanación se encuentra en el diálogo con el Señor.",
    "En la entrega sin reservas aparece la paz.",
    "Ama lo que te sucede; Dios, ahí, te acompaña y te habla.",
    "Lo que da sentido a todo es la presencia del amor.",
    "El Señor, en el domingo, siempre te habla sobre lo que te conviene.",
    "Dios, con su presencia, nos regala su paciencia.",
    "Dios es imprevisible hasta con el regalo de la paz.",
    "Todo es oportunidad de intensidad de escucha.",
    "En todo momento y en toda circunstancia, los hermanos en primer plano.",
    "Las maravillas las hace Dios en quien en Él confía.",
    "Sé peregrino de amor; todo brilla y madura, si, con amor, dejas que pase.",
    "Deja que el fuego del amor de Dios penetre en tu corazón.",
    "Ten siempre una mirada de bondad y de amor; es lo único que vale.",
    "Que tu vida sea reflejo del silencio sonoro de Dios.",
    "Amor y silencio es la comunión perfecta.",
    "Lo sabio y útil es sentirse amado por Dios.",
    "A lo poquito que nosotros le damos, Dios responde con su generosidad sin medida.",
    "Atento a la escucha de Dios; su voz se mezcla en todo lo que te acontece.",
    "Siempre se dice lo oportuno, si se dice desde la paz.",
    "Toda tu vida que respire ambiente de Dios.",
    "Tu vida se enriquece si hace felices a los demás.",
    "Dios ama nuestra sencillez y pobreza.",
    "La plegaria es la fuente que nunca se agota.",
    "Solo el encuentro con Dios y con los hermanos da plenitud a nuestra vida.",
    "Si nuestra respuesta es de amor, siempre acertaremos.",
    "Salir de nosotros mismos es privilegio del amor.",
    "Todo en tu vida muestra un nuevo camino de amor.",
    "La oscuridad es fruto de la mediocridad. La luz aparece en la entrega.",
    "Dios habla contigo, si eres fiel en las cosas pequeñas.",
    "Dios te mira con bondad; ese es tu camino.",
    "La fuerza y la vida está en la paz que recibes de Dios. Supera todas tus dificultades.",
    "Tu paz ser reflejo de la voluntad de Dios.",
    "No son opiniones nuestra vida; es fe y abandono en quien es respuesta a todos nuestros deseos.",
    "Nunca hay soledad para quien en Dios confía.",
    "Si ponemos delante el nosotros, siempre hay acogida.",
    "La paz es alejarse de tantos ídolos.",
    "La alegría está y radica en la esperanza.",
    "Guarda la calma y la paz en toda situación; ese es el camino.",
    "Dios es felicidad y claridad, si a Él te abandonas.",
    "Solo el amor transforma el sufrimiento.",
    "La escuela del amor reside en el sufrimiento.",
    "Descubre quien contempla.",
    "La claridad del camino la da la escucha.",
    "La fuerza más grande que siempre te acompaña es la fraternidad.",
    "Tu vida es siempre novedad creadora con Dios y con los hermanos.",
    "Con Dios, solo existe descanso en el alma.",
    "Tu amistad con Dios, fuente de todos los gozos.",
    "El gozo de servir es la liberación de la mente.",
    "Todo fracaso queda sanado, si nos acompaña la confianza del Señor.",
    "Nada resiste a la fuerza de la oración.",
    "Es el camino que se nos muestra: Dios y los hermanos. No existe la soledad.",
    "Todos los conflictos se minimizan ante la vivencia de la fraternidad.",
    "La presencia de Dios solo es, y siempre, amorosa.",
    "Desde la pequeñez todo es claridad.",
    "El amor y el corazón libre caminan juntos.",
    "Si en todo pones la paz del Señor, tu fuerza y victoria está garantizada.",
    "Toda claridad fluye de la oración.",
    "Si en tus dificultades, llenas de paz a los demás, es la prueba evidente de que Dios está contigo.",
    "El Señor es tu paz.",
    "El Señor es la paz que nunca falla.",
    "Que Dios te acompañe con su luz y su paz en estos momentos.",
    "Lo importante es tener el espíritu siempre dispuesto a recibir los dones de Dios. Adelante.",
    "Sé paciente; la paciencia es la gran virtud que permite escuchar los pasos de Dios.",
    "Todo, con la fe, se convierte en un gran encuentro de amor.",
    "Tu vida es de alegría, si en todo alabas al Señor.",
    "En todo momento, gracias a Dios.",
    "La respuesta válida la da Dios con la plegaria; Dios es fiel.",
    "La felicidad está en todo lo que tienes al alcance de la mano.",
    "La bienaventuranza es CAMINAR CON DIOS.",
    "Tu realidad es sentirte, con el Señor, BIENAVENTURADO.",
    "Un abrazo de paz y perdón.",
    "Solo Dios es dador de aquello que nos sobrepasa; solo que quiere ser el protagonista.",
    "Dios llena a quien se entrega; ese es el camino de la paz.",
    "Para Dios, no existen las cargas; Él es bondad y delicadeza.",
    "Si los demás son los protagonistas, ese día lo has aprovechado.",
    "No lo olvides, la paz y el amor no lo conseguimos nosotros; es regalo del Señor.",
    "En la constancia, se realiza el milagro de nuestra madurez y paz.",
    "El cansancio no tiene ninguna fuerza si te acompaña  la plegaria.",
    "La plegaria te hace escuchar el murmullo de amor de Dios.",
    "No te alejes del Espíritu; encontrarás el camino que te conviene.",
    "Todo egoísmo o interés personal se diluye ante la fuerza del Espíritu.",
    "Nuestro castillo interior es inexpugnable, si Experimentamos la fuerza de ser familia divina.",
    "La validez y eficacia de tu vida te la marca el amor con que vives todo cuanto te acontece.",
    "Una gran fiesta de Todos los Santos; es nuestro camino y nuestra paz.",
    "Tu vida siempre brillará si le acompaña la esperanza.",
    "Vivir la paz es llenarse de agradecimiento y confianza.",
    "Ser fieles al Señor nos abre las puertas de la claridad.",
    "El secreto de la sabiduría Dios lo coloca en tu confianza en Él.",
    "Siempre optar por el bien; Dios te acompañará con su gozo y satisfacción.",
    "Lo que quita todos los miedos es la confianza en el Señor.",
    "Que tu plegaria sea siempre por los demás; esa es la fuente de la eficacia de tu vida.",
    "La felicidad es tu abandono en Dios.",
    "El amor de Dios es la fuerza que todo lo convierte en luz.",
    "Sé constante y paciente; Ahí siempre aparece la paz.",
    "Es muy sencillo; Dios lo hace así, al alcance del corazón. Siembra de amor de Dios toda tu vida y te acompañará el gozo.",
    "Lo que de verdad eres es lo que te da la paz.",
    "Experimenta el gozo de dejar en manos de Dios todo lo que no podemos controlar. Es el descanso del alma.",
    "Lo que alas al corazón es la esperanza.",
    "Dar a los demás lo oportuno, es consecuencia de nuestro contacto con Dios.",
    "Siempre escucha; Dios es la voz más clara y más poderosa.",
    "A quien hay que escuchar es a Dios y empezar por renunciar a uno mismo.",
    "Un corazón libre siempre discierne las necesidades de los demás.",
    "No lo olvides, tu seguridad y tu paz la misericordia del Señor.",
    "Mira el árbol de la cruz; todo en Él se suaviza.",
    "El Cristo Rey pone su trono en nuestro corazón; esa es nuestra seguridad y fuerza.",
    "Nuestra vida debe ser un constante e infinito amor a los demás; así nos ama el Señor a nosotros.",
    "Goza, disfruta de tener un corazón lleno de bondad. Todo será bueno.",
    "En tu vida, siempre presentes, Dios y los hermanos.",
    "Vive con intensidad cada momento de tu vida; contiene todo lo que necesitas para ser amado y para amar.",
    "Tu vida será claridad, si es el Señor quien la ilumina.",
    "Es muy importante: no seamos maestros de nosotros mismos; si somos discípulos, sabremos leer siempre los mensajes de cuanto nos acontece.",
    "Es la intensidad de tu interior quien aligera el camino exterior.",
    "Lo que da brillo a nuestros ojos es la virtud de la esperanza.",
    "Muy importante: siempre Dios el protagonista; todo vuelve a su orden.",
    "De todo es el Señor quien inspira cada pensamiento.",
    "Atiende a este signo de la fe; si nuestro conflicto es intenso, es que estamos en soledad; Dios es siempre compañía y nos regala SU SUAVIDAD.",
    "El camino de la alegría y la paz lo va marcando nuestra entrega generosa a la voluntad de Dios.",
    "A escuchar lo que conviene nos lo muestra la intensidad de nuestra plegaria.",
    "Nunca decaigas, tu desierto el trono en el que Dios realiza el milagro de tu transformación.",
    "Nuestro camino es la pequeñez, la humildad; Dios ya hará sus maravillas.",
    "Nuestra vida es un continuo reto a superar; siempre aparece la luz,  si hay paciencia y confianza.",
];




